<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\catalog\ports.json" LogicalName="catalog.ports.json" Condition="Exists('..\..\catalog\ports.json')" />
    <EmbeddedResource Include="..\..\catalog\ports.overrides.json" LogicalName="catalog.ports.overrides.json" />
    <EmbeddedResource Include="..\..\catalog\roles.json" LogicalName="catalog.roles.json" />
    <EmbeddedResource Include="Render\diagram.css" LogicalName="render.diagram.css" />
    <EmbeddedResource Include="Render\diagram.js" LogicalName="render.diagram.js" />
    <EmbeddedResource Include="Render\panzoom.js" LogicalName="render.panzoom.js" />
    <EmbeddedResource Include="Render\library.js" LogicalName="render.library.js" />
  </ItemGroup>

</Project>
